language: android

jdk: oraclejdk8

sudo: false

notifications:
  email:
    recipients:
      - manni.cse@gmail.com
  on_success: never # default: change
  on_failure: always # default: always

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2        #Build tool version
    - android-25                #targate api version

    # Additional components
    - extra-android-support
    - extra-android-m2repository

script:
  - echo "Travis branch is $TRAVIS_BRANCH"    #Print out which branch it is.
  - echo "Travis branch is in pull request $TRAVIS_PULL_REQUEST"    #Print out pull request number.
  - bash gradlew test jacocoTestReport #Run junit tests and report

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"