commit:
  message:
    patterns:
      - '^#[0-9+]' #GitHub issues
approvals:
  minimum: 1
  ignore: pr_opener # do not count approval from PR opener
  ignore: none
  pattern: "^(:\\+1:|👍)$"
  veto:
    pattern: "^(:\\-1:|👎)$"
specification:
  title:
    minimum-length:
      enabled: true
      length: 8
