# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane
fastlane_version "1.64.0"

# This is the minimum version number required.
# Update this, if you use features of a newer version

# Usage examples:
# fastlane --verbose --env ci lint build_url:$BUILD_URL build_number:$BUILD_NUMBER adb:$ADB_PATH
# Runs lint for CI environment, with injected build_url from jenkins providing also the ADB path
#
# fastlane --verbose --env ci test build_url:$BUILD_URL build_number:$BUILD_NUMBER adb:$ADB_PATH
# Runs test action for CI environment, with injected build_url from jenkins providing also the ADB path
#
# fastlane --verbose --env ci instrumentationtest build_url:$BUILD_URL build_number:$BUILD_NUMBER adb:$ADB_PATH
# Runs instrumentation tests action for CI environment, with injected build_url from jenkins providing also the ADB path

default_platform :android

platform :android do

  before_all do
    $environment = ENV["ENVIRONMENT"]
  end

  desc "Runs all unit tests"
  lane :test do
    gradle(task: 'test', flags: '--no-daemon')
  end

  desc "Runs all instrumentation tests"
  lane :instrumentationtest do |options|

    # TODO upload the test APK to TestDroid

  end

  after_all do |lane, options|

    $build_number = options[:build_number]

    if lane.to_s == "test"
        # hipchat(from: "MsJenkins", message: "#{$environment}-#{$build_number}: Android core library successfully Unit Tested!", custom_color: "yellow" , channel: "Fleek%20Android", success: true)
        # No instrumentation tests running at the moment bring test to green color until we have maven upload task
        hipchat(from: "MsJenkins", message: "#{$environment}-#{$build_number}: Android core library successfully Unit Tested!", channel: "Fleek%20Android", success: true)
    end

  end

  error do |lane, exception, options|

    if lane.to_s == "test"
        hipchat(from: "MsJenkins", message_format:"html", message: $environment + ": Android core unit test failed...! <a href="+options[:build_url]+">ERROR LOG</a>", channel: "Fleek%20Android", success: false)
    end

  end
end
